// Generated by js_of_ocaml
//# buildInfo:effects=false, kind=cma, use-js-string=true, version=5.6.0

//# unitInfo: Provides: Inline_test_config
(function
  (globalThis){
   "use strict";
   var runtime = globalThis.jsoo_runtime;
   function pre_test_hook(_a_){return 0;}
   var Inline_test_config = [0, pre_test_hook];
   runtime.caml_register_global(0, Inline_test_config, "Inline_test_config");
   return;
  }
  (globalThis));

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLjAsImZpbGUiOiJpbmxpbmVfdGVzdF9jb25maWcuY21hLmpzIiwic291cmNlUm9vdCI6IiIsIm5hbWVzIjpbInByZV90ZXN0X2hvb2siXSwic291cmNlcyI6WyIvVXNlcnMvc3Zpc2hudXMvLm9wYW0vZ3J2LXRlc3QvbGliL3BweF9pbmxpbmVfdGVzdC9jb25maWcvaW5saW5lX3Rlc3RfY29uZmlnLm1sIl0sIm1hcHBpbmdzIjoiOzs7Ozs7OztZQUlJQSxtQjtnQ0FBQUE7OztFIiwic291cmNlc0NvbnRlbnQiOlsibW9kdWxlIHR5cGUgUyA9IHNpZ1xuICB2YWwgcHJlX3Rlc3RfaG9vayA6IHVuaXQgLT4gdW5pdFxuZW5kXG5cbmxldCBwcmVfdGVzdF9ob29rID0gaWdub3JlXG4iXX0=
