// Generated by js_of_ocaml
//# buildInfo:effects=false, kind=cma, use-js-string=true, version=5.6.0

//# unitInfo: Provides: Variantslib
//# unitInfo: Requires: Base__Variantslib
(function
  (globalThis){
   "use strict";
   var runtime = globalThis.jsoo_runtime, Variantslib = [0];
   runtime.caml_register_global(0, Variantslib, "Variantslib");
   return;
  }
  (globalThis));

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLjAsImZpbGUiOiJ2YXJpYW50c2xpYi5jbWEuanMiLCJzb3VyY2VSb290IjoiIiwibmFtZXMiOltdLCJzb3VyY2VzIjpbXSwibWFwcGluZ3MiOiI7Ozs7Ozs7Ozs7O0UiLCJzb3VyY2VzQ29udGVudCI6W119
