// Generated by js_of_ocaml
//# buildInfo:effects=false, kind=cma, use-js-string=true, version=5.6.0

//# unitInfo: Provides: Ppx_compare_lib
//# unitInfo: Requires: Base__Ppx_compare_lib
(function
  (globalThis){
   "use strict";
   var
    runtime = globalThis.jsoo_runtime,
    global_data = runtime.caml_get_global_data(),
    Base_Ppx_compare_lib = global_data.Base__Ppx_compare_lib,
    phys_equal = Base_Ppx_compare_lib[1],
    compare_abstract = Base_Ppx_compare_lib[2],
    equal_abstract = Base_Ppx_compare_lib[3],
    Comparable = Base_Ppx_compare_lib[4],
    Equal = Base_Ppx_compare_lib[5],
    Builtin = Base_Ppx_compare_lib[6],
    Ppx_compare_lib =
      [0,
       phys_equal,
       compare_abstract,
       equal_abstract,
       Comparable,
       Equal,
       Builtin];
   runtime.caml_register_global(1, Ppx_compare_lib, "Ppx_compare_lib");
   return;
  }
  (globalThis));

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLjAsImZpbGUiOiJwcHhfY29tcGFyZV9saWIuY21hLmpzIiwic291cmNlUm9vdCI6IiIsIm5hbWVzIjpbXSwic291cmNlcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O0UiLCJzb3VyY2VzQ29udGVudCI6W119
