// Generated by js_of_ocaml
//# buildInfo:effects=false, kind=cma, use-js-string=true, version=5.6.0

//# unitInfo: Provides: Jane_street_headers
(function
  (globalThis){
   "use strict";
   var runtime = globalThis.jsoo_runtime, Jane_street_headers = [0];
   runtime.caml_register_global(0, Jane_street_headers, "Jane_street_headers");
   return;
  }
  (globalThis));

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLjAsImZpbGUiOiJqYW5lX3N0cmVldF9oZWFkZXJzLmNtYS5qcyIsInNvdXJjZVJvb3QiOiIiLCJuYW1lcyI6W10sInNvdXJjZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7OztFIiwic291cmNlc0NvbnRlbnQiOltdfQ==
