// Generated by js_of_ocaml
//# buildInfo:effects=false, kind=cma, use-js-string=true, version=5.6.0

//# unitInfo: Provides: Ppx_hash_lib
//# unitInfo: Requires: Base__Ppx_hash_lib
(function
  (globalThis){
   "use strict";
   var
    runtime = globalThis.jsoo_runtime,
    global_data = runtime.caml_get_global_data(),
    Base_Ppx_hash_lib = global_data.Base__Ppx_hash_lib,
    Std = Base_Ppx_hash_lib[1],
    Hashable = Base_Ppx_hash_lib[2],
    Ppx_hash_lib = [0, Std, Hashable];
   runtime.caml_register_global(1, Ppx_hash_lib, "Ppx_hash_lib");
   return;
  }
  (globalThis));

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLjAsImZpbGUiOiJwcHhfaGFzaF9saWIuY21hLmpzIiwic291cmNlUm9vdCI6IiIsIm5hbWVzIjpbXSwic291cmNlcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7Ozs7Ozs7Ozs7OztFIiwic291cmNlc0NvbnRlbnQiOltdfQ==
