// Generated by js_of_ocaml
//# buildInfo:effects=false, kind=cma, use-js-string=true, version=5.6.0

//# unitInfo: Provides: Ppx_quickcheck_runtime__
(function
  (globalThis){
   "use strict";
   var runtime = globalThis.jsoo_runtime, Ppx_quickcheck_runtime = [0];
   runtime.caml_register_global
    (0, Ppx_quickcheck_runtime, "Ppx_quickcheck_runtime__");
   return;
  }
  (globalThis));

//# unitInfo: Provides: Ppx_quickcheck_runtime__Quickcheckable
(function
  (globalThis){
   "use strict";
   var
    runtime = globalThis.jsoo_runtime,
    Ppx_quickcheck_runtime_Quickch = [0];
   runtime.caml_register_global
    (0,
     Ppx_quickcheck_runtime_Quickch,
     "Ppx_quickcheck_runtime__Quickcheckable");
   return;
  }
  (globalThis));

//# unitInfo: Provides: Ppx_quickcheck_runtime
(function(globalThis){
   "use strict";
   var runtime = globalThis.jsoo_runtime, Ppx_quickcheck_runtime = [0];
   runtime.caml_register_global
    (0, Ppx_quickcheck_runtime, "Ppx_quickcheck_runtime");
   return;
  }
  (globalThis));

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLjAsImZpbGUiOiJwcHhfcXVpY2tjaGVja19ydW50aW1lLmNtYS5qcyIsInNvdXJjZVJvb3QiOiIiLCJuYW1lcyI6W10sInNvdXJjZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7Ozs7RTs7Ozs7Ozs7Ozs7Ozs7O0U7Ozs7Ozs7Ozs7RSIsInNvdXJjZXNDb250ZW50IjpbXX0=
