// Generated by js_of_ocaml
//# buildInfo:effects=false, kind=cma, use-js-string=true, version=5.6.0

//# unitInfo: Provides: Ppx_log_types
(function
  (globalThis){
   "use strict";
   var runtime = globalThis.jsoo_runtime, Ppx_log_types = [0];
   runtime.caml_register_global(0, Ppx_log_types, "Ppx_log_types");
   return;
  }
  (globalThis));

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLjAsImZpbGUiOiJwcHhfbG9nX3R5cGVzLmNtYS5qcyIsInNvdXJjZVJvb3QiOiIiLCJuYW1lcyI6W10sInNvdXJjZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7OztFIiwic291cmNlc0NvbnRlbnQiOltdfQ==
